export const DEFAULT_SEARCHES = [
  "React Native",
  "Frontend Engineer",
  "React Developer",
  "Next.js",
  "TypeScript",
  "Expo",
  "Node.js",
  "Backend",
  "Software Engineer",
  "Full Stack",
  "Founding Engineer",
  "AI Engineer",
  "Machine Learning",
  "GenAI",
  "Remote Developer",
  "Hiring React",
  "Hiring Frontend",
  "Hiring Software Engineer",
] as const;

export const DEFAULT_SEARCH_INTERVAL_MINUTES = 15;

/**
 * Semantic synonym groups. Matching is preferred over exact keyword
 * matching: a post mentioning "RN" is treated like it mentions
 * "React Native". Keys and entries are lower case.
 */
export const TOPIC_SYNONYMS: Record<string, string[]> = {
  "react native": [
    "rn",
    "react native",
    "react-native",
    "cross platform",
    "mobile engineer",
    "mobile developer",
    "expo",
  ],
  frontend: [
    "front end",
    "frontend",
    "front-end",
    "web engineer",
    "web developer",
    "ui engineer",
    "react developer",
    "nextjs",
    "next.js",
  ],
  nextjs: ["nextjs", "next.js", "next js"],
  typescript: ["typescript", "ts"],
  "software engineer": [
    "software engineer",
    "software developer",
    "swe",
    "sde",
    "backend engineer",
    "backend developer",
    "full stack",
    "fullstack",
  ],
  "full stack": ["full stack", "fullstack", "full-stack"],
  "founding engineer": [
    "founding engineer",
    "founding developer",
    "co-founder",
    "early engineer",
    "founder",
  ],
  "ai engineer": [
    "ai engineer",
    "ml engineer",
    "machine learning engineer",
    "llm",
    "genai",
    "generative ai",
    "prompt engineer",
    "ml",
  ],
  "machine learning": [
    "machine learning",
    "ml",
    "deep learning",
    "llm",
    "llms",
    "foundation model",
  ],
  genai: ["genai", "generative ai", "llm", "llms", "gpt"],
  remote: ["remote", "remote-first", "work from home", "wfh", "distributed team"],
  node: ["node", "nodejs", "node.js"],
  backend: ["backend", "back end", "back-end", "api engineer", "server engineer"],
};

/** Short "hiring" verb phrases that strongly indicate a live opening. */
export const HIRING_VERBS = [
  "we're hiring",
  "we are hiring",
  "we're looking for",
  "we are looking for",
  "we need",
  "hiring a",
  "hiring an",
  "hiring for",
  "we want to hire",
  "is hiring",
  "are hiring",
  "looking for a",
  "looking for an",
  "looking to hire",
  "recruiting",
  "open role",
  "open position",
  "job opening",
  "vacancy",
  "want to join",
  "join our team",
  "join us",
  "we have an opening",
  "we have openings",
  "dm me if interested",
  "dm me",
  "apply here",
  "applications open",
];

/** Phrases that indicate the post is NOT announcing a current opening. */
export const NEGATIVE_INDICATORS = [
  "just hired",
  "hired a",
  "hired an",
  "i hired",
  "we hired",
  "recently hired",
  "hired our",
  "no longer hiring",
  "closed the role",
  "role is filled",
  "position filled",
  "hiring freeze",
  "we are not hiring",
  "tutorial",
  "course",
  "certification",
  "bootcamp",
  "learn to code",
  "my interview",
  "interview experience",
  "resume review",
  "salary negotiation",
  "layoffs",
  "laid off",
  "got laid off",
  "job search tips",
  "open to work",
  "recruiter tips",
  "how to get hired",
  "job interview tips",
];

export const EMPLOYMENT_TYPES = [
  "full-time",
  "part-time",
  "contract",
  "internship",
  "trainee",
  "freelance",
] as const;
