import { betterAuth } from "better-auth";
import { prismaAdapter } from "better-auth/adapters/prisma";
import { getPrismaClient } from "@lhm/database";
import type { Env } from "../config/env.js";

/**
 * Creates the BetterAuth instance bound to Prisma and the frontend origin.
 * The returned instance is framework-agnostic; Fastify mounting lives in
 * ./plugin.ts.
 */
export function createAuth(env: Env) {
  const socialProviders =
    env.GOOGLE_CLIENT_ID && env.GOOGLE_CLIENT_SECRET
      ? {
          google: {
            clientId: env.GOOGLE_CLIENT_ID,
            clientSecret: env.GOOGLE_CLIENT_SECRET,
          },
        }
      : undefined;

  return betterAuth({
    appName: "LinkedIn Hiring Monitor",
    baseURL: env.BETTER_AUTH_URL,
    secret: env.BETTER_AUTH_SECRET,
    database: prismaAdapter(getPrismaClient(), { provider: "postgresql" }),
    trustedOrigins: [...env.CORS_ORIGINS, env.BETTER_AUTH_URL],
    emailAndPassword: {
      enabled: true,
      minPasswordLength: 8,
      requireEmailVerification: false,
      sendResetPassword: async () => {
        // Email delivery is wired in Phase 7 (notifications). Password
        // reset links are generated by BetterAuth via its own flow.
      },
    },
    socialProviders,
    session: {
      expiresIn: 60 * 60 * 24 * 7, // 7 days
      updateAge: 60 * 60 * 24, // sliding: refresh if active within 24h
    },
    user: {
      additionalFields: {
        role: {
          type: "string",
          defaultValue: "USER",
          required: false,
          input: false, // role is only assigned server-side
        },
      },
    },
    advanced: {
      cookiePrefix: "lhm",
    },
  });
}

export type Auth = ReturnType<typeof createAuth>;

export type AuthUser = {
  id: string;
  email: string;
  name: string | null;
  image: string | null;
  role: string;
};
